version: '3.5'
services:
  alice:
    build:
      context: ./node/
    volumes:
      - ${DATA_PATH}/alice/:/home/beam/data/
    ports:
      - "11001:11001"
    environment:
      - OWNER_KEY=${ALICE_OWNER_KEY}
      - MINER_KEY=${ALICE_MINER_KEY}
      - PEER=bob:11002
      - PORT=11001
  bob:
    build:
      context: ./node/
    volumes:
      - ${DATA_PATH}/bob/:/home/beam/data/
    ports:
      - "11002:11002"
    depends_on:
      - alice
    environment:
      - OWNER_KEY=${BOB_OWNER_KEY}
      - MINER_KEY=${BOB_MINER_KEY}
      - PEER=alice:11001
      - PORT=11002
  jim:
    build:
      context: ./node/
    volumes:
      - ${DATA_PATH}/jim/:/home/beam/data/
    ports:
      - "11003:11003"
    depends_on:
      - bob
    environment:
      - OWNER_KEY=${JIM_OWNER_KEY}
      - MINER_KEY=${JIM_MINER_KEY}
      - PEER=alice:11001,bob:11002
      - PORT=11003
  api:
    build:
      context: ./wallet-api/
    restart: always
    volumes:
      - ${DATA_PATH}/api/:/home/beam/data/
    ports:
      - "11011:11011"
    environment:
      - NODE_ADR=jim:11003
      - SEED_PHRASE=${JIM_SEED_PHRASE}
      - WALLET_PASS=1
    depends_on:
      - jim
  geth:
    build: ./eth/
    volumes:
      - ${DATA_PATH}/eth/:/home/geth/data/
    stop_signal: SIGINT
    stop_grace_period: 20s
    ports:
      - "4321:4321"
      - "8543:8543"
      - "8546:8546"

  # beam2eth_relay:
  #   build:
  #     context: ./../beam-bridge-ethrelay/
  #   volumes:
  #     - ${DATA_PATH}/ethrelay/:/home/ethrelay/data/
  #   environment:
  #     - RELAYER_SCRIPT=beam2eth_relay.js
  #     - BEAM_HOST=api
  #     - ETH_HTTP_PROVIDER=http://geth:8543
  #     - BEAM_BRIDGE_CID=40306461ecccb777b308643bd6499f9e22c7c6373edb11aae1d32f112c4a79ac

  #   depends_on:
  #     - api
  #     - geth

  # eth2beam_relay:
  #   build:
  #     context: ./../beam-bridge-ethrelay/
  #   volumes:
  #     - ${DATA_PATH}/ethrelay/:/home/ethrelay/data/
  #   environment:
  #     - RELAYER_SCRIPT=eth2beam_relay.js
  #     - BEAM_HOST=api
  #     - ETH_HTTP_PROVIDER=http://geth:8543
  #     - ETH_WEBSOCKET_PROVIDER=ws://geth:8546
  #   depends_on:
  #     - api
  #     - geth

  beam2usdt_relay:
    build:
      context: ./../beam-bridge-ethrelay/
    volumes:
      - ${DATA_PATH}/ethrelay/USDT/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_HOST=api
      - ETH_HTTP_PROVIDER=http://geth:8543
      - BEAM_BRIDGE_CID=2acc70ebd1bdda9d58c543e83560a35f5f9b06a1861ebde83500790c790d92fe
      - ETH_PIPE_CONTRACT_ADDRESS=0x950eedbEa0A4267028EAceAAb229633E5A9cC226
      - ETH_SENDER=0xFC63595A89699A742502e03d4021Be5dBfc2dD38
      - ETH_TOKEN_CONTRACT=0xC9A07C43f05eA5ad147d5cC4176DF6481287e3AD
      - ETH_SENDER_PRIVATE_KEY=0x..
      - ETH_SIDE_DECIMALS=6
    depends_on:
      - api
      - geth

  usdt2beam_relay:
    build:
      context: ./../beam-bridge-ethrelay/
    volumes:
      - ${DATA_PATH}/ethrelay/USDT/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_HOST=api
      - ETH_HTTP_PROVIDER=http://geth:8543
      - ETH_WEBSOCKET_PROVIDER=ws://geth:8546
      - BEAM_BRIDGE_CID=2acc70ebd1bdda9d58c543e83560a35f5f9b06a1861ebde83500790c790d92fe
      - ETH_PIPE_CONTRACT_ADDRESS=0x950eedbEa0A4267028EAceAAb229633E5A9cC226
      - ETH_SENDER=0xFC63595A89699A742502e03d4021Be5dBfc2dD38
      - ETH_TOKEN_CONTRACT=0xC9A07C43f05eA5ad147d5cC4176DF6481287e3AD
      - ETH_SENDER_PRIVATE_KEY=0x..
      - ETH_SIDE_DECIMALS=6
    depends_on:
      - api
      - geth

  beam2dai_relay:
    build:
      context: ./../beam-bridge-ethrelay/
    volumes:
      - ${DATA_PATH}/ethrelay/DAI/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=beam2eth_relay.js
      - BEAM_HOST=api
      - ETH_HTTP_PROVIDER=http://geth:8543
      - BEAM_BRIDGE_CID=8d16dab3c94df2edc7e946daadb7df406f920ee0447bedc8744c57a89c1f1fbd
      - ETH_PIPE_CONTRACT_ADDRESS=0xFF8713638b73b371D6a28C7C7852Aa57a0C9A3D2
      - ETH_SENDER=0x321a9Ce506fAA594a6A59d49eb0b344CA9802577
      - ETH_TOKEN_CONTRACT=0x373e337F18977237fB2e33E028F51dfDfA576B20
      - ETH_SENDER_PRIVATE_KEY=0x..
      - ETH_SIDE_DECIMALS=18
    depends_on:
      - api
      - geth

  dai2beam_relay:
    build:
      context: ./../beam-bridge-ethrelay/
    volumes:
      - ${DATA_PATH}/ethrelay/DAI/:/home/ethrelay/data/
    environment:
      - RELAYER_SCRIPT=eth2beam_relay.js
      - BEAM_HOST=api
      - ETH_HTTP_PROVIDER=http://geth:8543
      - ETH_WEBSOCKET_PROVIDER=ws://geth:8546
      - BEAM_BRIDGE_CID=8d16dab3c94df2edc7e946daadb7df406f920ee0447bedc8744c57a89c1f1fbd
      - ETH_PIPE_CONTRACT_ADDRESS=0xFF8713638b73b371D6a28C7C7852Aa57a0C9A3D2
      - ETH_SENDER=0x321a9Ce506fAA594a6A59d49eb0b344CA9802577
      - ETH_TOKEN_CONTRACT=0x373e337F18977237fB2e33E028F51dfDfA576B20
      - ETH_SENDER_PRIVATE_KEY=0x..
      - ETH_SIDE_DECIMALS=18
    depends_on:
      - api
      - geth